version: '3.1'
services:
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask:0.0.1
        container_name: flask
        volumes:
            - ./:/code/
        environment:
            - FLASK_APP=/code/app.py
            - VIRTUAL_HOST=test.localhost
            - VIRTUAL_PORT=5000
        command: flask run --host=0.0.0.0
        ports:
            - 5000:5000
        restart: always


networks:
  default:
    external:
      name: nginx-proxy